server:
  address:     ":8080"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  path:    "./var/log"
  level:   "all"
  stdout:  true
  ctxKeys: ["RequestId", "UserId"]
  writerColorEnable: true  # 日志文件带有颜色

database:
  logger:
  - path:   "./var/log"
    level:  "all"
    stdout: true
  default:
    link:  "mysql:root:123456@tcp(192.168.0.110:3306)/hiolabsDB?loc=Local&parseTime=true"
    debug: true

redis:
  default:
    address: 192.168.0.110:6379
    expire: 900
