// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package goods

import (
	"mall/api/goods"
)

type ControllerV1 struct{}

func NewV1() goods.IGoodsV1 {
	return &ControllerV1{}
}
