// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package search

import (
	"mall/api/search"
)

type ControllerV1 struct{}

func NewV1() search.ISearchV1 {
	return &ControllerV1{}
}
