// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package cart

import (
	"mall/api/cart"
)

type ControllerV1 struct{}

func NewV1() cart.ICartV1 {
	return &ControllerV1{}
}
