// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package address

import (
	"mall/api/address"
)

type ControllerV1 struct{}

func NewV1() address.IAddressV1 {
	return &ControllerV1{}
}
