// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package footprint

import (
	"mall/api/footprint"
)

type ControllerV1 struct{}

func NewV1() footprint.IFootprintV1 {
	return &ControllerV1{}
}
