// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsGoodsGalleryDao is internal type for wrapping internal DAO implements.
type internalHiolabsGoodsGalleryDao = *internal.HiolabsGoodsGalleryDao

// hiolabsGoodsGalleryDao is the data access object for table hiolabs_goods_gallery.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsGoodsGalleryDao struct {
	internalHiolabsGoodsGalleryDao
}

var (
	// HiolabsGoodsGallery is globally public accessible object for table hiolabs_goods_gallery operations.
	HiolabsGoodsGallery = hiolabsGoodsGalleryDao{
		internal.NewHiolabsGoodsGalleryDao(),
	}
)

// Fill with you ideas below.
