// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsOrderExpressDao is internal type for wrapping internal DAO implements.
type internalHiolabsOrderExpressDao = *internal.HiolabsOrderExpressDao

// hiolabsOrderExpressDao is the data access object for table hiolabs_order_express.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsOrderExpressDao struct {
	internalHiolabsOrderExpressDao
}

var (
	// HiolabsOrderExpress is globally public accessible object for table hiolabs_order_express operations.
	HiolabsOrderExpress = hiolabsOrderExpressDao{
		internal.NewHiolabsOrderExpressDao(),
	}
)

// Fill with you ideas below.
