// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsAdminDao is internal type for wrapping internal DAO implements.
type internalHiolabsAdminDao = *internal.HiolabsAdminDao

// hiolabsAdminDao is the data access object for table hiolabs_admin.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsAdminDao struct {
	internalHiolabsAdminDao
}

var (
	// HiolabsAdmin is globally public accessible object for table hiolabs_admin operations.
	HiolabsAdmin = hiolabsAdminDao{
		internal.NewHiolabsAdminDao(),
	}
)

// Fill with you ideas below.
