// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsRegionDao is internal type for wrapping internal DAO implements.
type internalHiolabsRegionDao = *internal.HiolabsRegionDao

// hiolabsRegionDao is the data access object for table hiolabs_region.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsRegionDao struct {
	internalHiolabsRegionDao
}

var (
	// HiolabsRegion is globally public accessible object for table hiolabs_region operations.
	HiolabsRegion = hiolabsRegionDao{
		internal.NewHiolabsRegionDao(),
	}
)

// Fill with you ideas below.
