// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsSearchHistoryDao is internal type for wrapping internal DAO implements.
type internalHiolabsSearchHistoryDao = *internal.HiolabsSearchHistoryDao

// hiolabsSearchHistoryDao is the data access object for table hiolabs_search_history.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsSearchHistoryDao struct {
	internalHiolabsSearchHistoryDao
}

var (
	// HiolabsSearchHistory is globally public accessible object for table hiolabs_search_history operations.
	HiolabsSearchHistory = hiolabsSearchHistoryDao{
		internal.NewHiolabsSearchHistoryDao(),
	}
)

// Fill with you ideas below.
