// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsFreightTemplateGroupDao is internal type for wrapping internal DAO implements.
type internalHiolabsFreightTemplateGroupDao = *internal.HiolabsFreightTemplateGroupDao

// hiolabsFreightTemplateGroupDao is the data access object for table hiolabs_freight_template_group.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsFreightTemplateGroupDao struct {
	internalHiolabsFreightTemplateGroupDao
}

var (
	// HiolabsFreightTemplateGroup is globally public accessible object for table hiolabs_freight_template_group operations.
	HiolabsFreightTemplateGroup = hiolabsFreightTemplateGroupDao{
		internal.NewHiolabsFreightTemplateGroupDao(),
	}
)

// Fill with you ideas below.
