// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsNoticeDao is internal type for wrapping internal DAO implements.
type internalHiolabsNoticeDao = *internal.HiolabsNoticeDao

// hiolabsNoticeDao is the data access object for table hiolabs_notice.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsNoticeDao struct {
	internalHiolabsNoticeDao
}

var (
	// HiolabsNotice is globally public accessible object for table hiolabs_notice operations.
	HiolabsNotice = hiolabsNoticeDao{
		internal.NewHiolabsNoticeDao(),
	}
)

// Fill with you ideas below.
