// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsGoodsDao is internal type for wrapping internal DAO implements.
type internalHiolabsGoodsDao = *internal.HiolabsGoodsDao

// hiolabsGoodsDao is the data access object for table hiolabs_goods.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsGoodsDao struct {
	internalHiolabsGoodsDao
}

var (
	// HiolabsGoods is globally public accessible object for table hiolabs_goods operations.
	HiolabsGoods = hiolabsGoodsDao{
		internal.NewHiolabsGoodsDao(),
	}
)

// Fill with you ideas below.
