// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsSettingsDao is internal type for wrapping internal DAO implements.
type internalHiolabsSettingsDao = *internal.HiolabsSettingsDao

// hiolabsSettingsDao is the data access object for table hiolabs_settings.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsSettingsDao struct {
	internalHiolabsSettingsDao
}

var (
	// HiolabsSettings is globally public accessible object for table hiolabs_settings operations.
	HiolabsSettings = hiolabsSettingsDao{
		internal.NewHiolabsSettingsDao(),
	}
)

// Fill with you ideas below.
