// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsProductDao is internal type for wrapping internal DAO implements.
type internalHiolabsProductDao = *internal.HiolabsProductDao

// hiolabsProductDao is the data access object for table hiolabs_product.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsProductDao struct {
	internalHiolabsProductDao
}

var (
	// HiolabsProduct is globally public accessible object for table hiolabs_product operations.
	HiolabsProduct = hiolabsProductDao{
		internal.NewHiolabsProductDao(),
	}
)

// Fill with you ideas below.
