// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsFootprintDao is internal type for wrapping internal DAO implements.
type internalHiolabsFootprintDao = *internal.HiolabsFootprintDao

// hiolabsFootprintDao is the data access object for table hiolabs_footprint.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsFootprintDao struct {
	internalHiolabsFootprintDao
}

var (
	// HiolabsFootprint is globally public accessible object for table hiolabs_footprint operations.
	HiolabsFootprint = hiolabsFootprintDao{
		internal.NewHiolabsFootprintDao(),
	}
)

// Fill with you ideas below.
