// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsCategoryDao is internal type for wrapping internal DAO implements.
type internalHiolabsCategoryDao = *internal.HiolabsCategoryDao

// hiolabsCategoryDao is the data access object for table hiolabs_category.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsCategoryDao struct {
	internalHiolabsCategoryDao
}

var (
	// HiolabsCategory is globally public accessible object for table hiolabs_category operations.
	HiolabsCategory = hiolabsCategoryDao{
		internal.NewHiolabsCategoryDao(),
	}
)

// Fill with you ideas below.
