// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsAddressDao is internal type for wrapping internal DAO implements.
type internalHiolabsAddressDao = *internal.HiolabsAddressDao

// hiolabsAddressDao is the data access object for table hiolabs_address.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsAddressDao struct {
	internalHiolabsAddressDao
}

var (
	// HiolabsAddress is globally public accessible object for table hiolabs_address operations.
	HiolabsAddress = hiolabsAddressDao{
		internal.NewHiolabsAddressDao(),
	}
)

// Fill with you ideas below.
