// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsOrderDao is internal type for wrapping internal DAO implements.
type internalHiolabsOrderDao = *internal.HiolabsOrderDao

// hiolabsOrderDao is the data access object for table hiolabs_order.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsOrderDao struct {
	internalHiolabsOrderDao
}

var (
	// HiolabsOrder is globally public accessible object for table hiolabs_order operations.
	HiolabsOrder = hiolabsOrderDao{
		internal.NewHiolabsOrderDao(),
	}
)

// Fill with you ideas below.
