// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsShipperDao is internal type for wrapping internal DAO implements.
type internalHiolabsShipperDao = *internal.HiolabsShipperDao

// hiolabsShipperDao is the data access object for table hiolabs_shipper.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsShipperDao struct {
	internalHiolabsShipperDao
}

var (
	// HiolabsShipper is globally public accessible object for table hiolabs_shipper operations.
	HiolabsShipper = hiolabsShipperDao{
		internal.NewHiolabsShipperDao(),
	}
)

// Fill with you ideas below.
