// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsFreightTemplateDetailDao is internal type for wrapping internal DAO implements.
type internalHiolabsFreightTemplateDetailDao = *internal.HiolabsFreightTemplateDetailDao

// hiolabsFreightTemplateDetailDao is the data access object for table hiolabs_freight_template_detail.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsFreightTemplateDetailDao struct {
	internalHiolabsFreightTemplateDetailDao
}

var (
	// HiolabsFreightTemplateDetail is globally public accessible object for table hiolabs_freight_template_detail operations.
	HiolabsFreightTemplateDetail = hiolabsFreightTemplateDetailDao{
		internal.NewHiolabsFreightTemplateDetailDao(),
	}
)

// Fill with you ideas below.
