// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsExceptAreaDao is internal type for wrapping internal DAO implements.
type internalHiolabsExceptAreaDao = *internal.HiolabsExceptAreaDao

// hiolabsExceptAreaDao is the data access object for table hiolabs_except_area.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsExceptAreaDao struct {
	internalHiolabsExceptAreaDao
}

var (
	// HiolabsExceptArea is globally public accessible object for table hiolabs_except_area operations.
	HiolabsExceptArea = hiolabsExceptAreaDao{
		internal.NewHiolabsExceptAreaDao(),
	}
)

// Fill with you ideas below.
