// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsShowSettingsDao is internal type for wrapping internal DAO implements.
type internalHiolabsShowSettingsDao = *internal.HiolabsShowSettingsDao

// hiolabsShowSettingsDao is the data access object for table hiolabs_show_settings.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsShowSettingsDao struct {
	internalHiolabsShowSettingsDao
}

var (
	// HiolabsShowSettings is globally public accessible object for table hiolabs_show_settings operations.
	HiolabsShowSettings = hiolabsShowSettingsDao{
		internal.NewHiolabsShowSettingsDao(),
	}
)

// Fill with you ideas below.
