// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsAdDao is internal type for wrapping internal DAO implements.
type internalHiolabsAdDao = *internal.HiolabsAdDao

// hiolabsAdDao is the data access object for table hiolabs_ad.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsAdDao struct {
	internalHiolabsAdDao
}

var (
	// HiolabsAd is globally public accessible object for table hiolabs_ad operations.
	HiolabsAd = hiolabsAdDao{
		internal.NewHiolabsAdDao(),
	}
)

// Fill with you ideas below.
