// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mall/internal/dao/internal"
)

// internalHiolabsUserDao is internal type for wrapping internal DAO implements.
type internalHiolabsUserDao = *internal.HiolabsUserDao

// hiolabsUserDao is the data access object for table hiolabs_user.
// You can define custom methods on it to extend its functionality as you wish.
type hiolabsUserDao struct {
	internalHiolabsUserDao
}

var (
	// HiolabsUser is globally public accessible object for table hiolabs_user operations.
	HiolabsUser = hiolabsUserDao{
		internal.NewHiolabsUserDao(),
	}
)

// Fill with you ideas below.
