// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package order

import (
	"mall/api/order"
)

type ControllerV1 struct{}

func NewV1() order.IOrderV1 {
	return &ControllerV1{}
}
