// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package region

import (
	"mall/api/region"
)

type ControllerV1 struct{}

func NewV1() region.IRegionV1 {
	return &ControllerV1{}
}
